/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/



#include <stdio.h>
#include <stdlib.h>
#include "uart_driver.h"
#include "timer.h"
#include "lcd.h"
#include "keypad.h"

//------------Values------------------------
#define read_mem_msg	"A: Read Memory"
#define write_mem_msg 	"B: Write Memory"
#define dump_mem_msg	"C: Dump Memory"
#define help_msg 		"D: Next Option"
#define hex_mode_msg	"*: Hex Mode"
#define binary_mode_msg "#: Binary Mode"
#define hex_input_msg 	"0x"
#define binary_input_msg "0b"

#define F_CPU 16000000UL

void option_menu(char input){
	int flag = 1;
	int frame_menu = 1;	//Help screen to tell user what to do
	while(flag){
		if(frame_menu == 1){
			lcd_print_string(read_mem_msg);
			lcd_set_position(1,0);
			lcd_print_string(help_msg);
		}
		else if(frame_menu == 2){
			lcd_print_string(write_mem_msg);
			lcd_set_position(1,0);
			lcd_print_string(help_msg);
		}
		else if(frame_menu == 3){
			lcd_print_string(dump_mem_msg);
			lcd_set_position(1,0);
			lcd_print_string(help_msg);
		}

		do{
			input = keypad_getchar();
		}while(input != 'A' && input != 'B' && input != 'C' && input != 'D');

		if(input == 'D'){
			lcd_clear();
			if(frame_menu == 3){
				frame_menu = 1;
			}
			else{
				frame_menu++;
			}
		}
		else if(input == 'A' || input == 'B' || input == 'C'){
			flag = 0;
		}
	}
}

int input_menu(char input){
	lcd_clear();
	lcd_print_string(hex_mode_msg);
	lcd_set_position(1,0);
	lcd_print_string(binary_mode_msg);
	
	do{
		input = keypad_getchar();
	}while(input != '*' && input != '#');

	if(input == '*'){
		return 1;
	}
	else{
		return 2;
	}
}

int bob(){
	char[8] input = '\0';
	char in = '\0';
	for(int i=0; i<8; i++){
		do{
			in = keypad_getchar;
		}while(in == '\0');
		char[i] = in;
	}
	lcd_print_string()
}

// main
int main(void){
	lcd_setup();
	keypad_setup();
	int col = 0;
	int row = 0;
	int input_option = 0;	//Input: 1 = hex 2 = decimal
	char input = '\0';
	while(1==1){
		option_menu(input);
		input_option = input_menu(input);
		lcd_clear();
		if(input_option ==  1){
			lcd_print_string(hex_input_msg);
		}
		else{
			lcd_print_string(binary_input_msg);
		}
	}
}

